config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  namespace :api, {format: 'json'} do
    namespace :v1 do
      resources :posts, only: [:index]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    resources :users
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    member do
      get :user_show_posts, :like_posts, :followings, :followers
    end
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :rankings, only: [:index]
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index]
    resources :posts, only: [:index]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  genre       :string(20)       not null
#  ingredients :string(200)      default("・ \n・ \n・ \n・ \n・"), not null
#  memo        :string(200)      not null
#  title       :string(20)       not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
class Post < ApplicationRecord
  has_one_attached :image
  validates :title, presence: true, length: { maximum: 20 }
  validates :genre, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validates :ingredients, presence: true, length: { maximum: 200 }
  validates :memo, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def display_image
    image.variant(resize: '1000^').processed
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate, only: %i[index]
  before_action :baria_admin_user, only: %i[index]

  def index
    @posts = Post.all.page(params[:page]).per(10)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  def index
    @posts = Post.all.with_attached_image.order(updated_at: 'DESC')

    render json: @posts.map { |post|
      post.as_json.merge({ image: url_for(post.image) })
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, only: %i[new create edit update destroy]
  before_action :baria_user, only: %i[edit update destroy]

  def index
  end

  def show
    set_post
    @comments = @post.comments.page(params[:page]).per(10).order(created_at: 'DESC')
    @comment = Comment.new
    @like = Like.new
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.image.attach(params[:post][:image])

    if @post.save
      redirect_to post_path(@post), notice: '新規投稿しました'
    else
      render :new, notice: '新規投稿に失敗しました'
    end
  end

  def edit
    set_post
  end

  def update
    set_post

    if @post.update(post_params)
      redirect_to post_path(@post), notice: '投稿を更新しました'
    else
      render :edit, notice: '投稿の編集に失敗しました'
    end
  end

  def destroy
    set_post
    @post.destroy
    redirect_to root_url unless current_user.admin?
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :genre, :ingredients, :memo)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def baria_user
    redirect_to root_url(current_user) unless Post.find(params[:id]).user.id.to_i == current_user.id || current_user.admin?
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/shared/_comments_form.html.slim
- unless browser.device.mobile?
  #comment-form
    - if user_signed_in?
      .card-body.text-center.rounded.m-3.app-color-light= form_with model: [@post, @comment], local: true do |c|
        = c.text_field :content, id: 'Content', class: 'form-control border-dark'
        = c.hidden_field :post_id, value: @post.id
        = c.submit 'コメントする', class: 'comment-form-button'
    - else
      .card-body.text-center.rounded.m-3.app-color-light
        = link_to 'ログインしてコメントする', login_path, data: {"turbolinks" => false}, class: 'login-comment-form-button'

- else
  #comment-form
    - if user_signed_in?
      .card-body.text-center.rounded.m-3.app-color-light= form_with model: [@post, @comment], local: true do |c|
        = c.text_field :content, id: 'Content', class: 'form-control border-dark'
        = c.hidden_field :post_id, value: @post.id
        = c.submit 'コメントする', class: 'mobile-comment-form-button'
    - else
      .card-body.text-center.rounded.m-3.app-color-light
        = link_to 'ログインしてコメントする', login_path, data: {"turbolinks" => false}, class: 'mobile-login-comment-form-button'

app/views/posts/shared/_comments_index.html.slim
- unless browser.device.mobile?
  #comments-pagination
    = paginate @comments, remote: true
    - @comments.each do |comment|
      div[id="comment-#{ comment.id }"]
        .container.bg-light.rounded.border
          .card-text
            = link_to user_path(comment.user), data: {"turbolinks" => false}
              = image_tag comment.user.display_image, class: 'resize-image rounded-circle', style: 'width: 50px; height: 50px;'
            p.m-3.d-inline-block= comment.user.username
            p.m-3.d-inline-block.p-wrap-90= comment.content
          - if user_signed_in?
            - if current_user.id == comment.user_id || current_user.admin?
              .d-flex.justify-content-end.align-items-center
                .mr-3
                  = simple_time(comment[:created_at])
                = link_to 'コメントを削除', post_comment_path(@post, comment), method: :delete, data: {"turbolinks" => false}, remote: true, class: 'comment-delete-button'
    = paginate @comments, remote: true

- else
  #comments-pagination
    = paginate @comments, remote: true
    - @comments.each do |comment|
      div[id="comment-#{ comment.id }"]
        .container.bg-light.rounded.border
          .card-text
            = link_to user_path(comment.user), data: {"turbolinks" => false}
              = image_tag comment.user.display_image, class: 'resize-image rounded-circle', style: 'width: 100px; height: 100px;'
            h3.m-3.d-inline-block= comment.user.username
            h3.m-3.d-inline-block.p-wrap-90= comment.content
          - if user_signed_in?
            - if current_user.id == comment.user_id || current_user.admin?
              .d-flex.justify-content-end.align-items-center
                .mr-3
                  = simple_time(comment[:created_at])
                = link_to 'コメントを削除', post_comment_path(@post, comment), method: :delete, data: {"turbolinks" => false}, remote: true, class: 'mobile-comment-delete-button'
    = paginate @comments, remote: true

app/views/posts/shared/_like.html.slim
.row.align-items-center
  .col-5
    = link_to post_likes_path(@post), method: :post, data: {"turbolinks" => false}, remote: true, id: 'like-btn'
      i.mdi.mdi-heart.like-btn
  .col-3
    div[id="likes"]= @likes_count

app/views/posts/shared/_like_button.html.slim
- unless browser.device.mobile?
  .row.align-items-center
    .col-5
      = link_to post_likes_path(@post), method: :post, data: {"turbolinks" => false}, remote: true, id: 'like-button'
        i.mdi.mdi-heart.like-button
    .col-3
      h3[id="likes"]= @likes_count

- else
  .row.align-items-center
    .col-5
      = link_to post_likes_path(@post), method: :post, data: {"turbolinks" => false}, remote: true, id: 'like-button'
        i.mdi.mdi-heart.mobile-like-button
    .col-2.ml-5
      h1[id="likes"]= @likes_count

app/views/posts/shared/_like_form.html.slim
div[id="like-form#{@post.id}"]
  - if user_signed_in?
    - if current_user.already_liked?(@post)
      = render 'posts/shared/unlike_button'
    - else
      = render 'posts/shared/like_button'
  -else
    .row.align-items-center
      .col-5= link_to login_path, data: {"turbolinks" => false}, id: 'like-button'
        i.mdi.mdi-heart.like-button
      .col-3
        div[id="likes"]= @likes_count

app/views/posts/shared/_unlike.html.slim
.row.align-items-center
  .col-5
    = link_to post_like_path(post_id: @post ,id: @post.likes[0].id), method: :delete, data: {"turbolinks" => false}, remote: true, id: 'unlike-btn'
      i.mdi.mdi-heart.unlike-btn
  .col-2
    div[id="likes"]= @likes_count

app/views/posts/shared/_unlike_button.html.slim
- unless browser.device.mobile?
  .row.align-items-center
    .col-5
      = link_to post_like_path(post_id: @post ,id: @post.likes[0].id), method: :delete, data: {"turbolinks" => false}, remote: true, id: 'unlike-button'
        i.mdi.mdi-heart.unlike-button
    .col-2
      h3[id="likes"]= @likes_count

- else
  .row.align-items-center
    .col-5
      = link_to post_like_path(post_id: @post ,id: @post.likes[0].id), method: :delete, data: {"turbolinks" => false}, remote: true, id: 'unlike-button'
        i.mdi.mdi-heart.mobile-unlike-button
    .col-2.ml-5
      h1[id="likes"]= @likes_count