config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  namespace :api, {format: 'json'} do
    namespace :v1 do
      resources :posts, only: [:index]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  devise_scope :user do
    resources :users
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    member do
      get :user_show_posts, :like_posts, :followings, :followers
    end
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :rankings, only: [:index]
    end
  end

  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    resources :users, only: [:index]
    resources :posts, only: [:index]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  profile                :string(200)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  username               :string(10)       not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :default_image

  has_one_attached :image

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

  validates :username, presence: true, length: { maximum: 10 }
  validates :profile, length: { maximum: 200 }

  def default_image
    image.attach(
      io: File.open(Rails.root.join('app', 'assets', 'images', 'default_user_image.png')),
      filename: 'default_user_image.png',
      content_type: 'image/png'
    ) unless image.attached?
  end

  def display_image
    image.variant(resize: '1000^').processed
  end

  def self.guest
    find_or_create_by!(
      username: 'ゲストユーザー',
      email: 'guest@example.com'
    ) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate, only: %i[index]
  before_action :baria_admin_user, only: %i[index]

  def index
    @users = User.all.page(params[:page]).per(10)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::API
  def index
    @user = User.find_by(id: current_user)

    render json: @user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_admin, only: :create
  before_action :check_guest, only: :create
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_admin, only: %i[update destroy]
  before_action :check_guest, only: %i[update destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(_resource)
    user_path(id: current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to user_path(id: current_user.id), notice: 'ゲストユーザーとしてログインしました。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :baria_admin_user, only: %i[destroy]
  before_action :set_user

  def show
    @relationshiops = @user.followings
  end

  def destroy
    @user.destroy
  end

  def user_show_posts
    @posts = @user.posts.all.page(params[:page]).per(10)
  end

  def like_posts
    @posts = @user.liked_posts.all.page(params[:page]).per(10)
  end

  def followings
    @users = @user.followings.page(params[:page]).per(10).order(created_at: 'DESC')
  end

  def followers
    @users = @user.followers.page(params[:page]).per(10).order(created_at: 'DESC')
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.js.slim
| $("#user-
= @user.id
| ").remove();

app/views/users/followers.html.slim
.container-fluid.app-color-light
  .text-center.text-light.p-4
    h1.title-design フォロワーページ

  .container
    .card.rounded-lg.app-color-sub-light
      .card-body
        = render 'users/shared/followers_index'

app/views/users/followers.js.slim
| $("#followers-pagination").html("
= j(render("users/shared/followers_index"))
| ");

app/views/users/followings.html.slim
.container-fluid.app-color-light
  .text-center.text-light.p-4
    h1.title-design フォローページ

  .container
    .card.rounded-lg.app-color-sub-light
      .card-body
        = render 'users/shared/followings_index'

app/views/users/followings.js.slim
| $("#followings-pagination").html("
= j(render("users/shared/followings_index"))
| ");

app/views/users/like_posts.html.slim
.container-fluid.app-color-light
  .text-center.text-light.p-4
    h1.title-design #{ @user.username }がいいねした投稿

  .container
    .card.rounded-lg.app-color-sub-light
      .card-body
        = render 'users/shared/like_posts_index'

app/views/users/like_posts.js.slim
| $("#like-posts-pagination").html("
= j(render("users/shared/like_posts_index"))
| ");

app/views/users/show.html.slim
- unless browser.device.mobile?
  .container-fluid.app-color-light
    .text-center.text-light.p-4
      - if current_user == @user
        h1.title-design マイプロフィール
      - else
        h1.title-design ユーザープロフィール

    - if flash.notice.present?
        .container
          .alert.alert-primary
            = flash.notice

    .container
      .card.rounded-lg.app-color-sub-light
        .card-body
          .row
            .col-5.card-img.mt-3.ml-5
              = image_tag @user.display_image, class: 'resize-image rounded-circle', style: 'width: 200px; height: 200px;'
            .col-5.card-body.mt-4
              h6 ユーザーネーム
              .container.bg-light.rounded
                h5.text-center.pt-2
                  = @user.username
              .row
                .col.text-center
                  = link_to 'フォロー', followings_user_path(@user), data: {"turbolinks" => false}, class: 'user-following-index-button'
                  .bg-light.rounded.shadow-lg.mt-1.mx-4
                    p#followings
                      =@user.followings.count
                .col.text-center
                  = link_to 'フォロワー', followers_user_path(@user), data: {"turbolinks" => false}, class: 'user-follower-index-button'
                  .bg-light.rounded.shadow-lg.mt-1.mx-4
                    p#followers
                      =@user.followers.count
          .card-body
            h6 プロフィール
            .container.bg-light.rounded
              .card-text
                p
                  = @user.profile
          .container.text-secondary.ml-3
            p ユーザー作成日時
            = simple_time(@user[:created_at])

          = render 'users/shared/follow_form', user: @user

    .container
      .card.rounded-lg.app-color-sub-light
        .row
          .col.text-center.m-2
            = link_to 'ユーザーの投稿', user_show_posts_user_path(@user), data: {"turbolinks" => false}, class: 'user-posts-index-button'
          .col.text-center.m-2
            = link_to 'いいねした投稿', like_posts_user_path(@user), data: {"turbolinks" => false}, class: 'user-like-index-button'

    - if current_user == @user || current_user.admin?
      .container
        .card.rounded-lg.app-color-sub-light
          .row
            .col.text-center.m-2
              = link_to 'ユーザーを編集', edit_user_registration_path, data: {'turbolinks' => false}, class: 'user-edit-button'
            .col.text-center.m-2
              = link_to 'ユーザーを削除', user_registration_path, method: :delete, data: {'turbolinks' => false, confirm: '本当にユーザーを削除しますか？'}, class: 'user-delete-button'

- else
  .container-fluid.app-color-light
    .text-center.text-light.p-4
      - if current_user == @user
        h1.title-design マイプロフィール
      - else
        h1.title-design ユーザープロフィール

    - if flash.notice.present?
        .container
          .alert.alert-primary
            = flash.notice

    .container
      .card.rounded-lg.app-color-sub-light
        .card-body
          .row
            .col-5.card-img.mt-3.ml-5
              = image_tag @user.display_image, class: 'resize-image rounded-circle', style: 'width: 250px; height: 250px;'
            .col-5.card-body.mt-4
              h4 ユーザーネーム
              .container.bg-light.rounded
                h2.text-center.pt-2
                  = @user.username
              .row
                .col.text-center
                  = link_to 'フォロー', followings_user_path(@user), data: {"turbolinks" => false}, class: 'mobile-user-following-index-button'
                  .bg-light.rounded.shadow-lg.mt-4
                    h2#followings
                      =@user.followings.count
                .col.text-center
                  = link_to 'フォロワー', followers_user_path(@user), data: {"turbolinks" => false}, class: 'mobile-user-follower-index-button'
                  .bg-light.rounded.shadow-lg.mt-4
                    h2#followers
                      =@user.followers.count
          .card-body
            h4 プロフィール
            .container.bg-light.rounded
              .card-text
                h3
                  = @user.profile
          .container.text-secondary.ml-3
            h4 ユーザー作成日時
            = simple_time(@user[:created_at])

          = render 'users/shared/follow_form', user: @user

    .container
      .card.rounded-lg.app-color-sub-light.mt-5
        .row
          .col.text-center
            = link_to 'ユーザーの投稿', user_show_posts_user_path(@user), data: {"turbolinks" => false}, class: 'mobile-user-posts-index-button'
          .col.text-center
            = link_to 'いいねした投稿', like_posts_user_path(@user), data: {"turbolinks" => false}, class: 'mobile-user-like-index-button'

    - if current_user == @user || current_user.admin?
      .container
        .card.rounded-lg.app-color-sub-light.mt-5
          .row
            .col.text-center
              = link_to 'ユーザーを編集', edit_user_registration_path, data: {'turbolinks' => false}, class: 'mobile-user-edit-button'
            .col.text-center
              = link_to 'ユーザーを削除', user_registration_path, method: :delete, data: {'turbolinks' => false, confirm: '本当にユーザーを削除しますか？'}, class: 'mobile-user-delete-button'

app/views/users/user_show_posts.html.slim
.container-fluid.app-color-light
  .text-center.text-light.p-4
    h1.title-design #{ @user.username }の投稿

  .container
    .card.rounded-lg.app-color-sub-light
      .card-body
        = render 'users/shared/user_show_posts_index'

app/views/users/user_show_posts.js.slim
| $("#user-show-posts-pagination").html("
= j(render("users/shared/user_show_posts_index"))
| ");